set -U fish_color_autosuggestion 777777
set -U fish_color_cancel \x2dr
set -U fish_color_command 00FF00
set -U fish_color_comment 30BE30
set -U fish_color_cwd green
set -U fish_color_cwd_root red
set -U fish_color_end FF7B7B
set -U fish_color_error A40000
set -U fish_color_escape 00a6b2
set -U fish_color_history_current \x2d\x2dbold
set -U fish_color_host normal
set -U fish_color_host_remote yellow
set -U fish_color_match \x2d\x2dbackground\x3dbrblue
set -U fish_color_normal normal
set -U fish_color_operator 00a6b2
set -U fish_color_param 30BE30
set -U fish_color_quote 00A400
set -U fish_color_redirection 7BFF7B
set -U fish_color_search_match bryellow\x1e\x2d\x2dbackground\x3dbrblack
set -U fish_color_selection white\x1e\x2d\x2dbold\x1e\x2d\x2dbackground\x3dbrblack
set -U fish_color_status red
set -U fish_color_user brgreen
set -U fish_color_valid_path \x2d\x2dunderline

